name: Python application CI/CD

on:
push:
  branches: [ main]
pull_request:
  branches: [main]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up python 3.12.9
        uses: actions/setup-python@v2
        with:
          python-version:3.12.9
        name:Install Dependencies
        run:
          python -m pip install --upgrade pip
          pip install unittest
        name: test with unittest
        run:
          python -m unittest discover -v

          

